# Site settings
title: Aro Blog
SEOTitle: 周泓宇的博客 | Aro
header-img: img/home-bg.jpg
email: iver31995@iCloud.com
description: "关于前端开发与设计 | 周泓宇，Web & Mobile Lover，Software Engineer，Developer | 这里是 @Aro周泓宇 的个人博客，与你一起发现更大的世界。"
keyword: "周泓宇, Aro周泓宇, Aro, 前端开发者, @Aro, 周泓宇的博客, Aro Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://zhouhongyu.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     iver31995
zhihu_username:     zhou-hong-yu-69-13
github_username:    AroZhou
jianshu_username:   b21ec5fd6535
# twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: arozhou

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]
ba_track_id: 1368bc4b60b20d92f24c12438c746e4e

# Google Analytics
ga_track_id: 'UA-145060107-1'            # Format: UA-xxxxxx-xx
ga_domain: zhouhongyu.top



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    # {
    #     title: "乱序",
    #     href: "http://mida.re/"
    # },{
    #     title: "前端外刊评论",
    #     href: "http://qianduan.guru/"
    # },{
    #     title: "天镶的博客",
    #     href: "http://lingyu.wang/"
    # },{
    #     title: "Luke 的自留地",
    #     href: "http://hmqk1995.github.io"
    # },{
    #     title: "Ebn's Blog",
    #     href: "http://ebnbin.com/"
    # },{
    #     title: "SmdCn's Blog",
    #     href: "http://blog.smdcn.net"
    # },{
    #     title: "David's Game",
    #     href: "https://www.ruoyaowu.com/"
    # },{
    #     title: "DHong Say",
    #     href: "http://dhong.co"
    # },{
    #     title: "尹峰以为",
    #     href: "http://ingf.github.io/"
    # },{
    #     title: "解旻的博客",
    #     href: "http://xieminis.me/"
    # }
]
